title: Adelaide Bioinformatics Workshop Hub
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
url: 'https://sagc-bioinformatics.github.io/community-organisation/'

include:
  - _pages
